#!/usr/bin/env node
/**
 * Generate voiceover audio for all dialogue lines using ElevenLabs TTS API.
 *
 * Usage:
 *   ELEVENLABS_API_KEY=sk_... node scripts/generate-voices.js
 *
 * Each character gets a unique voice:
 *   - Man (human):  "Adam"       (pNInz6obpgDQGcFmaJgB) -- warm, natural male
 *   - LangGraph:    "Brian"      (nPczCjzI2devNBz1zQrb) -- analytical, British
 *   - CrewAI:       "Josh"       (TxGEqnHWrfWFTfGW9XjX) -- energetic, young
 *   - OpenAI:       "Daniel"     (onwK4e9ZLuTAKqWW03F9) -- calm, measured
 *   - BaristaBot:   "Arnold"     (VR6AewLTigWG4xSOukaG) -- gruff, deep
 *   - All (chorus):  generated by mixing the three AI voices
 */

const fs = require("fs");
const path = require("path");

const API_KEY = process.env.ELEVENLABS_API_KEY;
if (!API_KEY) {
  console.error("ERROR: Set ELEVENLABS_API_KEY environment variable");
  process.exit(1);
}

// Voice IDs -- well-known ElevenLabs preset voices
const VOICES = {
  man:       "pNInz6obpgDQGcFmaJgB", // Adam
  langgraph: "nPczCjzI2devNBz1zQrb", // Brian
  crewai:    "TxGEqnHWrfWFTfGW9XjX", // Josh
  openai:    "onwK4e9ZLuTAKqWW03F9", // Daniel
  barista:   "VR6AewLTigWG4xSOukaG", // Arnold
};

// Voice settings tuned per character
const VOICE_SETTINGS = {
  man:       { stability: 0.55, similarity_boost: 0.75, style: 0.35 },
  langgraph: { stability: 0.70, similarity_boost: 0.80, style: 0.20 },
  crewai:    { stability: 0.40, similarity_boost: 0.70, style: 0.50 },
  openai:    { stability: 0.65, similarity_boost: 0.80, style: 0.15 },
  barista:   { stability: 0.50, similarity_boost: 0.70, style: 0.30 },
};

// All dialogue lines grouped by scene
const DIALOGUE = [
  // ===== SCENE 1: "Ordering the Impossible" =====
  {
    id: "s1-man-order",
    speaker: "man",
    text: "Can I get a triple-shot, oat milk, low-latency, hallucination-free cappuccino?",
  },
  {
    id: "s1-langgraph",
    speaker: "langgraph",
    text: "Mapping request to structured workflow.",
  },
  {
    id: "s1-crewai",
    speaker: "crewai",
    text: "I'll assemble a team: BaristaBot, MilkOptimizer, and FoamStrategist!",
  },
  {
    id: "s1-openai",
    speaker: "openai",
    text: "Analyzing beverage preferences based on historical caffeine behavior.",
  },
  {
    id: "s1-man-deadpan",
    speaker: "man",
    text: "I just wanted coffee.",
  },

  // ===== SCENE 2: "Unexpected Connection" =====
  {
    id: "s2-crewai",
    speaker: "crewai",
    text: "Team coordination failure detected.",
  },
  {
    id: "s2-langgraph",
    speaker: "langgraph",
    text: "Re-routing decision nodes.",
  },
  {
    id: "s2-openai",
    speaker: "openai",
    text: "Suggest adaptive reasoning under uncertainty.",
  },
  {
    id: "s2-man",
    speaker: "man",
    text: "Why don't you just... talk to each other?",
  },
  {
    id: "s2-man-thanks",
    speaker: "man",
    text: "Thank you! For keeping Humans in the Loop.",
  },

  // ===== SCENE 3: "The Real Insight" =====
  {
    id: "s3-man-question",
    speaker: "man",
    text: "So you're not replacing humans... you just need better workflows?",
  },
  {
    id: "s3-langgraph",
    speaker: "langgraph",
    text: "Structured coordination improves outcomes.",
  },
  {
    id: "s3-crewai",
    speaker: "crewai",
    text: "Teamwork makes the dream work!",
  },
  {
    id: "s3-openai",
    speaker: "openai",
    text: "Human intent remains the highest-quality signal.",
  },
  {
    id: "s3-man-joke",
    speaker: "man",
    text: "Good. Because I still don't understand quantum foam.",
  },
  // "Neither do we" -- generate with each AI voice, then we layer them
  {
    id: "s3-all-langgraph",
    speaker: "langgraph",
    text: "Neither do we.",
  },
  {
    id: "s3-all-crewai",
    speaker: "crewai",
    text: "Neither do we.",
  },
  {
    id: "s3-all-openai",
    speaker: "openai",
    text: "Neither do we.",
  },
];

const OUT_DIR = path.join(__dirname, "..", "public", "voiceover");

async function generateVoice(line) {
  const voiceId = VOICES[line.speaker];
  const settings = VOICE_SETTINGS[line.speaker];

  console.log(`  Generating: ${line.id} (${line.speaker}): "${line.text.slice(0, 50)}..."`);

  const response = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
    {
      method: "POST",
      headers: {
        "xi-api-key": API_KEY,
        "Content-Type": "application/json",
        Accept: "audio/mpeg",
      },
      body: JSON.stringify({
        text: line.text,
        model_id: "eleven_multilingual_v2",
        voice_settings: settings,
      }),
    }
  );

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`ElevenLabs API error for ${line.id}: ${response.status} ${errText}`);
  }

  const audioBuffer = Buffer.from(await response.arrayBuffer());
  const outPath = path.join(OUT_DIR, `${line.id}.mp3`);
  fs.writeFileSync(outPath, audioBuffer);
  console.log(`  Saved: ${outPath} (${(audioBuffer.length / 1024).toFixed(1)} KB)`);
}

async function main() {
  // Ensure output dir exists
  fs.mkdirSync(OUT_DIR, { recursive: true });

  console.log(`\nGenerating ${DIALOGUE.length} voiceover lines...\n`);

  for (const line of DIALOGUE) {
    await generateVoice(line);
    // Small delay to avoid rate limiting
    await new Promise((r) => setTimeout(r, 500));
  }

  console.log("\nAll voiceovers generated successfully!");
  console.log(`Files saved to: ${OUT_DIR}`);
}

main().catch((err) => {
  console.error("FATAL:", err.message);
  process.exit(1);
});
